INSERT INTO BOARD(TITLE,CONTENTS,WRITER) VALUES('하이하이','내가 주인공이니까','조의천');
INSERT INTO BOARD(TITLE,CONTENTS,WRITER) VALUES('지영쌤 오면 깜짝 파티해주자~','내가선물','김동현');
INSERT INTO BOARD(TITLE,CONTENTS,WRITER) VALUES('동현씨 그거 하면 고소당할듯.....','하지마셈','서지민');

COMMIT;

SELECT * FROM BOARD;
SELECT * FROM MEMBER;

